/* eslint-disable no-unused-vars */

const groupNames = {
  POSSIBILITY_SUPPORT: 'POSSIBILITY_SUPPORT',
  POSSIBILITY_OPPOSE: 'POSSIBILITY_OPPOSE',
  POSSIBILITY_INFO: 'POSSIBILITY_INFO',       // INFO_ONLY IS A DEPRECATED STATE, COMES THROUGH API AS NO_STANCE
  STORED_SUPPORT: 'STORED_SUPPORT',
  STORED_OPPOSE: 'STORED_OPPOSE',
  STORED_INFO: 'STORED_INFO',                 // INFO_ONLY IS A DEPRECATED STATE, COMES THROUGH API AS NO_STANCE
  DELETED: 'DELETED',
  DEFAULT: 'DEFAULT'
};

const colors = {
  POSS_SUPPORT_FOREGROUND: '#FFFFFF',
  POSS_SUPPORT_BACKGROUND: '#27af72',
  POSS_OPPOSE_FOREGROUND: '#FFFFFF',
  POSS_OPPOSE_BACKGROUND: '#fb6532',
  POSS_INFO_FOREGROUND: '#FFFFFF',
  POSS_INFO_BACKGROUND: '#7c7b7c',
  STORED_SUPPORT_FOREGROUND: '#28b074',
  STORED_SUPPORT_BACKGROUND: '#b4e7cd',
  STORED_OPPOSE_FOREGROUND: '#f16936',
  STORED_OPPOSE_BACKGROUND: '#f7c9b8',
  STORED_INFO_FOREGROUND: '#818082',
  STORED_INFO_BACKGROUND: '#dad8da',
  DELETED_FOREGROUND: '#aa0311',
  DELETED_BACKGROUND: '#f0c7c8',
}
